---
env:
  global:
  - VERSION="${TRAVIS_TAG}"
  - NAME=Detect4jAgent
language: java
before_install:
- chmod +x scripts/build.sh
install: true
jdk:
- openjdk8
  # - openjdk9
  # - openjdk10
  # - openjdk11
script: scripts/build.sh
jobs:
  include:
  - stage: deploy
    before_install:
    - chmod +x scripts/build.sh
    install: true
    jdk: openjdk8
    script: scripts/build.sh
    deploy:
      provider: releases
      api_key:
        secure: FBwm9mejQ0yZn+kwGDuByVvSSk3mXNU3zrfsHLV3oFaWGzIKz0IbL9Sf50cIxlsC7cYkW7kfsmWgMo2JpWHd07WxyWLczS9BqQdFnQRBdUuxqgzwtfxxisfhioxiqDwnR9esSvvyA2+tSMznlhmmT+NbyG6KvXbWcKjdncwkpKrqVzxBnlfe7EzHM601cArvgU3S7pRPTpTKYhjIUp373WkweL+LZ30CcmCQYQhnaipN1ermRdkECAiDkbx9KAJJdRWrlQ9+C0kbEgGYg2YOFv0ehB/fvzISTlGcSiyg8UIUGqdrke+OhBphQrDENLXkbYiPvtZcxLmDLOdBheXGipDJqZXxMCOm8FX43vmUN72GVGY25JLEAwhRciK5mMN3c1gKi50i2uMFEw+1uEkMDmoX7coWehaysxZ5Pm1GRXCBgCYD1l2yHz8ru+sf1Q/pAPqeaSBm7aS4xDQ8IEhpcw+9d9GSzm2CSFIb6rRYLAGH6KHc8BZsSuaFcIlh97cUq4F205u/UZH1pVX3T8eoZrVYjJ/UIQwg3a9q9WVblvCnKhnsHUGwydTyoZRxGXFe4TsW57cJ6qiMc3CzsSmERy6lFSdfWWACDGd+StLqq6+tQHwgu1lnNH5a7Cayd0+njhCVcoh2ZODUeCU53BirdV+hG+qXZambhbmrpCvGUmU=
      file_glob: true
      file:
      - build/libs/*
      skip_cleanup: true
      on:
        repo: theque5t/Detect4jAgent
        tags: true
