---
env:
  global:
    - VERSION="${TRAVIS_TAG}"
    - NAME=Log4jDetectorAgent
language: java
before_install:
  - chmod +x scripts/build.sh
install: true
jdk:
  - openjdk8
  # - openjdk9
  # - openjdk10
  # - openjdk11
script: scripts/build.sh
jobs:
  include:
    - stage: deploy
      before_install:
        - chmod +x scripts/build.sh
      install: true
      jdk: openjdk8
      script: scripts/build.sh
      deploy:
        provider: releases
        api_key:
          secure: "ICQKwkL/WZwrhkLI4SB3OPhCy19suPcxtdz/jA2Zl/UMInbe8t+Mqx5CvANdFHIsOfx03abIbF7juu2LXT++DuSZCbkkn37AZrDJzjf+qk3q+1oscKaZzDRlUjupj5mjOZV24hyQewRG6CKH2Qx5vr14fqRh0odUoEI7hBZCg0nUj1rP65fZWZac2PBO8tQ93OMdbSVe0zTrf+9aiXMeGaS9QcBGY2Ur7AEp8ipfkSof1xt2eZRZsHNVrmobwXnyaEVqoO5MurwR4+JfRJNiJV9imgPKzutUh7yZhNq4KKH5MYxj1RiyGXw5gisThFb85gPty8V6SAhD+11ytLkf/K/siwOILV4OxMb8HNzypGT3UgcAcQLoy1SsydIFQsAbINigGhoN+D//cszQhV9S8ilQeGetNM/qBzMukK5a88KUv2/xjerj7oCdNDZAv/J42FG5dfyXHSMdUsyPkKY0UlIYKK33Pe8ndD4wRa2x5et2xIIbnQpRXUnmOhbtRMlIBLq8EO3ILytk6Bff+7BKQbBfzc/UfJ7bvvvZcOAJjQ/J2ClSVZ4E8c8SxzNhaLrJYJSOfl3v+1ZJjbWAjgkdJenzRa5QLrxtUrbmf7Evz1/qtjeM8MEqgXpqIkAOLfSOHbFJGjXIMJHgCMf0Hd+qFWedgzUxbErfCbarTbzGXhY="
        file_glob: true
        file: 
          - build/libs/*
        skip_cleanup: true
        on:
          repo: theque5t/Log4jDetectorAgent
          tags: true
